### ISSUE TITLE
Support G3Bool and G3VectorBool?

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/so3g#116]
This came up in conversation with @jlashner -- should we support [G3Bool](https://cmb-s4.github.io/spt3g_software/moddoc_core.html?highlight=g3bool#spt3g-core-g3bool)?

Currently we don't, and on the ocs end we ensure bools don't make it to the Aggregator as of https://github.com/simonsobs/ocs/pull/229. However, as of https://github.com/CMB-S4/spt3g_software/commit/d5b304dc24de1b2d33c7d194a8d06afb6f610572 spt3g_software supports vectors of bools with `G3VectorBool` (missing this might have been what stopped us from supporting it initially?)

I just wanted to open up the topic for wider conversation.

**Comment by mhasself** [comment]
Sounds good to me.  Indeed G3VectorBool didn't exist when G3TimesampleMap was invented.

First step is to extend G3TimesampleMap to accept G3VectorBool.  Then make sure so3g.hk can deal with that.  Then ocs.

**Comment by mhasself** [comment]
Step 1 ... https://github.com/CMB-S4/spt3g_software/pull/72

**Comment by BrianJKoopman** [comment]
Thanks @mhasself. Just capturing our discussion from the other day. You'll make sure `so3g.hk` can deal with the new G3VectorBool in G3TimesampleMaps, then I'll update ocs with the latest so3g version and make sure it accepts bools on the Feeds.
