### ISSUE TITLE
Sort out wheel build test failures on Python 3.10

### ISSUE THREAD

**Issue by tskisner** [simonsobs/so3g#119]
Our nightly wheel test builds fail on python-3.10 because on those platforms the astropy packages gets built from source (since we require astropy < 5.0, which does not exist as wheels for 3.10).  Astropy 4.3.1 building in turn requires other dependencies which have since been updated in a non-compatible way.  Basically we are seeing a duplicate of this:

https://github.com/pallets/markupsafe/issues/284

Possible solutions are:

- Make our code work with astropy 5 (we'll need to do this anyway eventually) or
- Pre-install (and pin to old versions) the low-level packages needed to build astropy-4.3.1 in our wheel building environment.

This will need to be sorted out before the next tag.

**Comment by mhasself** [comment]
Where does our current < 5 requirement ultimately come from?  I have checked so3g and pixell at least and they don't seem to mind 5.0.1.

**Comment by tskisner** [comment]
I thought I saw unit test failures with astropy-5.  I will double check.

**Comment by tskisner** [comment]
Apparently astropy-5 is just fine, and lifting that fixes things.  Fixed in #120

**Comment by tskisner** [comment]
Closed by #120
