### ISSUE TITLE
so3g.proj: det_weights=0 isn't optimized away

### ISSUE THREAD

**Issue by mhasself** [simonsobs/so3g#147]
One can pass in custom cuts to avoid projecting dets that aren't of interest, but we should support short-circuits based on det_weights==0 too.

**Comment by tterasaki** [comment]
I am working in the branch of [single_det_map_modification](https://github.com/simonsobs/so3g/blob/a6341c405a7a758149e12f600bcb2f678089fa1c/src/Projection.cxx#L1393).

I have just added
```
if (det_wt == 0.) continue;
```
in the `to_map_single_thread`, `to_weight_map_single_thread`, `precomp_to_map_single_thread`, and `precomp_to_weight_map_single_thread`.

I am demonstrating it in `compute11:/so/home/tterasaki/code_dev/so3g_proj_singledetmaps_demo.ipynb`
(Actually I am not working in the compute11 as it was difficult to compile so3g in compute11. Its just for sharing)

The newer version works ~factor 2 faster when n_det is smaller than 100. Howerver when n_det is about 500 or larger, it gets super slow and slower than the 'restrict and makemap' method. I am not so familiar with c++, but I thought for-loop is not so bad operation in c++. So I do not understand why it is so slow. Do you have any idea, @mhasself ?

**Comment by mhasself** [comment]
Welcome to C / C++!  Indentation doesn't matter in C / C++.  Do have multiple statements in an "if" or "else" (or anything) block, surround them in {}.

So in C, this:
```
    if (something)
        thing1 = 2;
        thing2 = 9;
```
is the same as
```
    if (something)
        thing1 = 2;
    thing2 = 9;
```

Multiple statements in an if block need to be inside {}, like this:
```
    if (something) {
        thing1 = 2;
        thing2 = 9;
    }
```

**Comment by mhasself** [comment]
However, I don't see why that minor formatting issue would matter here (it's ok for the check to be outside of the if block).

I'm not sure why it would matter, but maybe the thread assignment is an issue?  What happens if you create P with threads=False?

**Comment by tterasaki** [comment]
Thanks Matthew! I was obsessed with python style before I know... Will fix later.

Without fixing the formatting issue, I tried the `threads=False` case by comparing the following two.
v2 is `threads=None` and v3 is `threads=False`. 

```Python
def make_singledetmaps_v2(aman, res=0.3*coords.DEG):
    wcs_kernel = coords.get_wcs_kernel('car', 0, 0, res)
    P = coords.P.for_tod(tod=aman, wcs_kernel=wcs_kernel, comps='T',)
    
    mT_dict = {}
    for di, det in enumerate(tqdm(aman.dets.vals)):
        det_weights = np.zeros(aman.dets.count, dtype='float32')
        det_weights[di] = 1.
        mT_weighted = P.to_map(tod=aman, comps='T', det_weights=det_weights)
        wT = P.to_weights(aman, comps='T', det_weights=det_weights)
        mT = P.remove_weights(signal_map=mT_weighted, weights_map=wT, comps='T')
        mT_dict[det] = mT
    return mT_dict
```

```Python
def make_singledetmaps_v3(aman, res=0.3*coords.DEG):
    wcs_kernel = coords.get_wcs_kernel('car', 0, 0, res)
    cuts = RangesMatrix([ Ranges.from_bitmask(np.zeros(aman.samps.count, dtype=bool)) for di in range(aman.dets.count)])
    P = coords.P.for_tod(tod=aman, wcs_kernel=wcs_kernel, comps='T', threads=False, cuts=cuts)
    
    mT_dict = {}
    for di, det in enumerate(tqdm(aman.dets.vals)):
        det_weights = np.zeros(aman.dets.count, dtype='float32')
        det_weights[di] = 1.
        
        mT_weighted = P.to_map(tod=aman, comps='T', det_weights=det_weights)
        wT = P.to_weights(aman, comps='T', det_weights=det_weights)
        mT = P.remove_weights(signal_map=mT_weighted, weights_map=wT, comps='T')
        mT_dict[det] = mT
    return mT_dict
```

It really changed the speed. v3 is 10 times faster than v2 with `N_det = 100`.
So it seems that the issue lies in multi-threading stuffs.
![image](https://github.com/simonsobs/so3g/assets/59273369/728fa189-1f40-4227-a989-7a961a7520a4)

**Comment by tterasaki** [comment]
Plotting the thread assignment with
```Python
n_dets = 50
n_scans = 5
res = 0.3 * coords.DEG
aman = make_dummy_aman(n_dets, n_scans)

wcs_kernel = coords.get_wcs_kernel('car', 0, 0, res)
P = coords.P.for_tod(tod=aman, wcs_kernel=wcs_kernel, comps='T', threads='domdir')
_, threads = P._get_proj_threads()

fig, ax = plt.subplots(4,4,figsize=(15,15))
ax = ax.ravel()
fig.suptitle("threads='domdir'", size=20)
for i_thread in range(n_threads)[:16]:
    thread_mask = threads[0][i_thread].mask()
    ax[i_thread].imshow(thread_mask, aspect=aman.samps.count/aman.dets.count)
    ax[i_thread].set_title(f'i_thread={i_thread} (/{n_threads})')
    ax[i_thread].set_xlabel('samps')
    ax[i_thread].set_ylabel('dets')
fig.tight_layout(rect=[0,0,1,0.96])
```
It looks like the following figure. (the first one is with `threads='domdir'` and the second one is with `threads='simple'`)
For both case, threading is done along the `samps`. It is undesirable for the singledet map purpose, isn't it?

![image](https://github.com/simonsobs/so3g/assets/59273369/49dba218-a35a-4943-8069-38dbbbae0344)

![download](https://github.com/simonsobs/so3g/assets/59273369/859a8bdd-8515-4495-9d50-2ccf30d0a2e4)

**Comment by tterasaki** [comment]
(Fixed the {} formatting)

**Comment by mhasself** [comment]
Ok, interesting.  This det_weights=0 optimization is going to be useful -- please PR it and we can get the basic changes merged quickly.  I really doubt any of the run time problems are directly related to that change... so they should be sorted out separately. 

I think 128 threads is probably too many!  I usually test with 8.  In tests I've done, the linear performance improvement does not survive all the way up to 10s of cores.  I think that's a common thing people have found in map-making projection profiling.  But also the "thread assignment" algorithms probably break down a lot unless the number of rows/cols in the map is much less than the number of threads (i.e. n_threads << n_pix**0.5).

The alignment of your thread assignment with sample index, across all detectors, suggests that all your detectors might have the same pointing ... which is probably true in your application, where the detector positions are not yet known.  So that mystery is solved.  The stripiness of the threading is really bad ... I think that's explained by using so many threads on a relatively small map.

**Comment by tterasaki** [comment]
I see. Ah, I did not care much about the threading parameters. I will check it later.
Yeah, the threading optimization looks independent of this PR. I will PR.

**Comment by mhasself** [comment]
Closing as complete -- happy to talk more about threading here or on Slack.
