### ISSUE TITLE
Meaning of "channel" in `hk.getdata`

### ISSUE THREAD

**Issue by ahincks** [simonsobs/so3g#15]
As far as I can tell, "channel" means the same things as "field". Could we consider switching to only using the nomenclature "field"? (I.e., `field_groups` instead of `channel_groups`, etc.) This could prevent confusion.

**Comment by mhasself** [comment]
I think you are totally right about that; let's sed channel -> field.

Whoever deals with this, please make sure the name fix is in a single commit with no additional functional or API changes.

**Comment by ahincks** [comment]
Resolved by PR #16.
