### ISSUE TITLE
HK logger does too much logging

### ISSUE THREAD

**Issue by newburgh** [simonsobs/so3g#151]
Katie: anyone know where this logger is coming from and how I can shut it up?

![image](https://github.com/simonsobs/ocs/assets/7266917/d16486d8-55fe-4106-b34f-5cf6482b3e6e)

**Comment by mhasself** [comment]
This is only noisy when running through Prefect, as I understand it.

We can turn down the verbosity in so3g but a better understanding of Prefect x Python logging is probably on the horizon.

**Comment by guanyilun** [comment]
prefect is logging at INFO level I think. Maybe this needs to be at DEBUG level? https://github.com/simonsobs/so3g/blob/master/python/hk/getdata.py#L315

**Comment by mhasself** [comment]
Resolved in #153
