### ISSUE TITLE
New G3 Vector Types for SO?

### ISSUE THREAD

**Issue by mhasself** [simonsobs/so3g#27]
This issue is intended to start a conversation about new data types we might want to have to store the SO TOD (both detector and ancillary streams) properly.  If some consensus is reached, the resulting work can be broken up and re-issued.

High-level concerns:

1.  FLAC provides very good compression for many of our signals, but the current G3Timestream forces the signal to lie in the dynamic range corresponding to 24-bit integers.  This is inconvenient in cases where the signal has a natural calibration that takes the meaningful part of the signal out of this range.  We thus desire to have FLAC compression and gain+offset transformations encoded in a vector object.

2.  G3Timestreams unpack to 64-bit floats.  This level of precision is basically never needed for anything.  It is definitely not needed to process detector data, which is the bulk of our data set.  Even if we just transform, on load, to float32, the additional RAM and processing overhead is a little silly.  So we want better support for unpacking timestreams directly to float32.

3.  Our Housekeeping data structure, G3IrregDouble, is ready for an upgrade.  The idea of storing timestamps co-sampled with 1 or more data vectors is good... but we need more flexibility in those data types.  Right now everything is uncompressed doubles, which is wasteful and actually has consequences because we sometimes want to look at HK on long times scales.  We should try to support, on equal footing, time-stamped streams of:
- float64, float32 (including with FLAC compression and gain+offset transforms).
- [u]int64/32/16/8.
- A string enumerator data type; for example to efficiently encode streams drawn from the set ["OK", "ERROR1", "ERROR2"].
- Strings.  The application here is log messages.

4.  Re-sampling algorithms that work on "normal" signals (detector timestreams, e.g.) do not work properly on signals that live on a periodic domain (such as HWP angles) or integer signals representing bit-masks (such as telescope status bits).  We should consider some form of annotation that would indicate, to a downstream consumer, that a field is periodic from [A, B).  For bit-masks, the equivalent minimal metadata would tell us what to do when trying to "down-sample" the sequence [0,1,1,0,0] into a single bit -- either we should AND those values together (to get 0 in this case), or OR them (to get 1).  (This isn't perfectly general but it would help us do the right thing much of the time.)

**Comment by nwhitehorn** [comment]
A few quick comments on the first two items.

1. The 24-bit limit is unfortunately a limitation of the reference encoder. One way to encode the high-order bits would be to use the multi-channel feature of the encoder (if FLAC is appropriate) and do the high- and low-order bits as a "stereo" signal, which might be more flexible than transformations.
2. We have an experimental branch that I can push to the public repository that adds single-precision encoding. It hasn't been merged because the round-off error turned out to matter for some applications (to my surprise) and because single- and double-precision timestreams are hard to mix on the C++ end without templating everything. I can at least push the branch to a branch on the public repository and would appreciate any thoughts you might have on it.

**Comment by mhasself** [comment]
Thanks Nathan, I'd be interested in seeing what you have for (2).

On point (1)... that's a neat idea, but does not address the fact that the resolution is always "1".  I'm as interested in cases where the unit is 0.000001 as in cases where the unit 10000.  [Aside on FLAC stereo -- do you mean to imply that there's an advantage in using FLAC's stereo mode rather than doing independent FLAC runs on the upper and lower bits?  Unfortunately I don't think 48-bit signals will have correlated bit sub-fields.]

**Comment by nwhitehorn** [comment]
I'll try to beat that branch into shape. For the second point, is FLAC actually the right answer here? It doesn't do anything especially magical -- for most data, it is basically equivalent to just delta-encoding after subtracting the best-fit line over some small region. The only magic it adds is finding bright lines and encoding them separately (using for HWP data). Depending on what exactly you want to encode, it might be easiest to add some non-FLAC compression.

**Comment by nwhitehorn** [comment]
I just pushed the single-precision code to a branch: https://github.com/CMB-S4/spt3g_software/tree/singleprecision

**Comment by mhasself** [comment]
This has largely been addressed with the introduction of G3TimesampleMap and G3SuperTimestream. (https://github.com/CMB-S4/spt3g_software/pull/17 and #98)
