### ISSUE TITLE
G3IndexedReader becomes unseekable once you reach EOF

### ISSUE THREAD

**Issue by mhasself** [simonsobs/so3g#35]
... or something like that.  This probably can't be fixed, so it should be documented.  It might be best to recommend that users only do "forward seeking".  That's "stream" compatible and probably not a deal-breaker for our use cases.

**Comment by BrianJKoopman** [comment]
Yeah, that's it. If you increase the number in the range for [the test](https://github.com/simonsobs/so3g/blob/f70b6149cd66e54c5aa91b2e1290549d1ef8fe76/test/test_indexed.py#L89) in `test_indexed.py`, then you'll see it won't seek afterwards.

**Comment by mhasself** [comment]
Addressed in #172
