### ISSUE TITLE
cmake problem on mac with python 3.7

### ISSUE THREAD

**Issue by jlashner** [simonsobs/so3g#36]
Trying to re-install so3g on my mac which has upgraded to python3.7, and I'm having trouble even though I'm able to successfully install spt3g.

cmake gives the error:
```
CMake Error at /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python3.7"
  (requested version 1.71.0) with any of the following names:

    boost_python3.7Config.cmake
    boost_python3.7-config.cmake

  Add the installation prefix of "boost_python3.7" to CMAKE_PREFIX_PATH or
  set "boost_python3.7_DIR" to a directory containing one of the above files.
  If "boost_python3.7" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindBoost.cmake:264 (find_package)
  CMakeLists.txt:44 (find_package)
```

It looks like the python cmake files are in `/usr/local/lib/cmake/boost_python-1.71.0`, which contains 
```
boost_python-config-version.cmake
boost_python-config.cmake
libboost_python-variant-mt-shared-py3.7.cmake
libboost_python-variant-mt-static-py3.7.cmake
libboost_python-variant-shared-py3.7.cmake
libboost_python-variant-static-py3.7.cmake
```

but specifying that dir as `boost_python3.7_DIR` doesn't change anything. Any ideas?

**Comment by mvlungu** [comment]
I had this same issue when installing with python 3.7 on the tiger cluster. A simple fix is to create "correctly" named symlinks to the existing cmake files:

```
mlungu@tigercpu:~/software/build/lib$ ls -l cmake/boost_python-1.70.0/
total 16
lrwxrwxrwx. 1 mlungu physics   25 Jun  4 11:42 boost_python3.7-config.cmake -> boost_python-config.cmake
lrwxrwxrwx. 1 mlungu physics   33 Jun  4 11:42 boost_python3.7-config-version.cmake -> boost_python-config-version.cmake
-rw-r--r--. 1 mlungu physics 3045 Jun  4 10:31 boost_python-config.cmake
-rw-r--r--. 1 mlungu physics  304 Jun  4 10:31 boost_python-config-version.cmake
lrwxrwxrwx. 1 mlungu physics   36 Jun  4 11:44 libboost_python3.7-variant-shared.cmake -> libboost_python-variant-shared.cmake
lrwxrwxrwx. 1 mlungu physics   36 Jun  4 11:45 libboost_python3.7-variant-static.cmake -> libboost_python-variant-static.cmake
-rw-r--r--. 1 mlungu physics 1716 Jun  4 10:31 libboost_python-variant-shared.cmake
-rw-r--r--. 1 mlungu physics 1549 Jun  4 10:31 libboost_python-variant-static.cmake
```

**Comment by jlashner** [comment]
Hmmm, cmake passed but then after I run `make` I get this error: 
```
ld: library not found for -lBoost::python3.7
```
Is there anything I have to do to upgrade besides upgrading `boost` and `boost-python3`?

**Comment by mvlungu** [comment]
It's been a while, but I also noticed that I made a renamed symlink to the boost python libraries in my local `lib/cmake/` directory:

```
drwxr-xr-x. 2 mlungu physics 4096 Jun  4 11:45 boost_python-1.70.0
lrwxrwxrwx. 1 mlungu physics   19 Jun  4 11:45 boost_python3.7-1.70.0 -> boost_python-1.70.0
```

**Comment by jlashner** [comment]
hmmm I think I linked that also. I thought I solved the problem by replacing the code in the CMakeLists.txt that set `Boost_PYTHON_TYPE` with the code that does it in spt3g's CMakeList, 
and that solved the cmake issue without having to make any links. Now when I try to run make I get this error:

```
Undefined symbols for architecture x86_64:
  "_omp_get_num_threads", referenced from:
      ProjectionEngine<Pointer<ProjFlat>, Pixelizor2_Flat, Accumulator<SpinT> >::pixel_ranges(boost::python::api::object, boost::python::api::object) in Projection.cxx.o
      ProjectionEngine<Pointer<ProjFlat>, Pixelizor2_Flat, Accumulator<SpinQU> >::pixel_ranges(boost::python::api::object, boost::python::api::object) in Projection.cxx.o
...
```
and 
```
  "_omp_get_thread_num", referenced from:
      ProjectionEngine<Pointer<ProjFlat>, Pixelizor2_Flat, Accumulator<SpinT> >::to_map_omp(boost::python::api::object, boost::python::api::object, boost::python::api::object, boost::python::api::object, boost::python::api::object, boost::python::api::object) in Projection.cxx.o
      ProjectionEngine<Pointer<ProjFlat>, Pixelizor2_Flat, Accumulator<SpinT> >::to_weight_map_omp(boost::python::api::object, boost::python::api::object, boost::python::api::object, boost::python::api::object, boost::python::api::object, boost::python::api::object) in Projection.cxx.o
...
```
Which seems to be a different problem that has to do with OMP, which I'm not using since I had trouble installing it on my mac. Is omp required now? I don't think it was before. @mhasself

**Comment by mhasself** [comment]
To suppress compilation of the Projection module, try commenting out Projection.cxx in CMakeLists.  If that doesn't work due to internal cross-dependencies, comment out all the openmp #pragma lines.  A more permanent solution (not sure if we want to go that route) would be to dodge those pragmas depending on a computed pre-processor variable, like spt3g does.

The logic for determining Boost_PYTHON_TYPE doesn't always work... but you can override it, see README.  Probably all you needed was
```cmake -DBoost_PYTHON_TYPE=python ..```

**Comment by mhasself** [comment]
@jlashner  I'd be interested to hear if Mac behaves better, now that we're leaning more on the cmake output from spt3g.  Otherwise, ok to close this?

**Comment by jlashner** [comment]
Unfortunately I was never to successfully install this on my machine. I stopped looking at this once so3g was added to the ocs-util docker. I'm fine with closing this issue.
