### ISSUE TITLE
RangesMatrix needs a copy method

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/so3g#52]
Ran in to this trying to make a copy of an `AxisManager` with some `RangesMatrix`s.

**Comment by kmharrington** [comment]
I think this might have been fixed with the recent push? But I'd also like to add "RangesMatrix need add functionality" as well. I'm up for trying to do that upgrade today. 

Also, is there a native "buffering" functionality to Ranges? I'm also interested in adding that.

**Comment by mhasself** [comment]
Yes, copy was added in #53 .  You mean add in the sense of `__add__`?  That makes complete sense, please do.

I'm ok with having buffering added.  New C++ methods "buffer" (in-place) and "buffered" (returns new object)?

**Comment by kmharrington** [comment]
yup, already got an `__add__` function working locally (just ripped from __mult__).  I'll see what I can do about buffering on the C++ side.

Question on the `Ranges` / `RangesMatrix`. Do we want their addition/multiplication to be commutative? Right now they're not, but it's some quick shape checks to make it work that way. 

I think I want them commutative, b/c I think I would rather "not have to keep track." Also it looks like `RangeMatrix * RangeMatrix` just finds the right axis to use, so that's already breaking "matrix algebra rules"

**Comment by kmharrington** [comment]
Wait, amend that a bit. it's that `RangesMatrix(1,M)  * RangesMatrix(N,M) == RangesMatrix(N,M) * RangesMatrix(1,M)`

**Comment by mhasself** [comment]
Not sure I understand the commutative vs. matrix algebra bit... my intention was that these would broadcast in the same way numpy arrays do, which I believe has commutativity.

Did #54 resolve this issue?

**Comment by kmharrington** [comment]
Most of it yeah. The commutativity thing is due to typing when we do `x*y.` If `x` is a `Ranges` it doesn't know how to multiply itself by a `RangesMatrix`. If we think that will be a problem let's open a new issue.
