### ISSUE TITLE
g3_to_array function doesn't work with current files

### ISSUE THREAD

**Issue by jlashner** [simonsobs/so3g#61]
I think I updated the smurf-streamer frame format to agree with the tod format documentation but now the `g3_to_array` function breaks with the new data files. Currently the TES Biases are written to a G3TimestreamMapp with the keys like `bias00`, `bias01`, ... and I'm getting the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-226dac7fb6f1> in <module>
      1 fname = '/data/timestreams/15906/1590616226_000.g3'
----> 2 times, data = g3_to_array(fname)

/usr/lib/python3/dist-packages/so3g/smurf/reader.py in g3_to_array(g3file, verbose)
     74     biasnums = []
     75     for num in frames[i]['tes_biases'].keys():
---> 76         biasnums.append(int(num))
     77     biasnums.sort()
     78     for b in biasnums:

ValueError: invalid literal for int() with base 10: 'bias00'
```

@laurensaunders the Smurf Recorder is currently running @ UCSD so if you want I can provide a recent g3 file.

**Comment by laurensaunders** [comment]
A recent g3 file would be really helpful if you can send me one

**Comment by kmharrington** [comment]
@laurensaunders  If you have access to `simons1` there are some files in `/mnt/so1/users/kmharrin/scratch_data/smurf_data_202006$` that should this error
