### ISSUE TITLE
Test and deploy with github actions

### ISSUE THREAD

**Issue by tskisner** [simonsobs/so3g#74]
Now that travis is changing its pricing model, it might be a good time to switch to github actions for tests.  I was working on using actions for wheel deployment, but we could use them for the general test case as well.

**Comment by BrianJKoopman** [comment]
Ah, I was wondering why I received a new "Welcome to Travis CI" email this morning, despite having my account for years. Here's the news on the new pricing model for others who might have missed it: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

The pipeline here can be migrated to GitHub Actions, definitely. It's the same structure I had configured on the ocs/socs repos. I can take care of that sometime soon.
