### ISSUE TITLE
"Report test coverage" is crashing on PR workflow

### ISSUE THREAD

**Issue by mhasself** [simonsobs/so3g#84]
Crashes with error like "Could not submit coverage: 422 Client Error: Unprocessable Entity for url"

E.g.
https://github.com/simonsobs/so3g/runs/1688921577
https://github.com/simonsobs/so3g/pull/79/checks?check_run_id=1724521743

@BrianJKoopman Have any ideas on this?

**Comment by BrianJKoopman** [comment]
The coverage on socs is doing the same thing. I'll look into it some more.

**Comment by BrianJKoopman** [comment]
The coveralls-python package updated recently, and now requires an additional flag to be thrown when called to specify the CI service used. Fix is here https://github.com/simonsobs/so3g/pull/85.
