### ISSUE TITLE
load_range function casts to integers

### ISSUE THREAD

**Issue by jlashner** [simonsobs/so3g#91]
Somehow this has gone unnoticed, but the load_range function cast some fields to integers when loaded. 

For example, I'm taking a look at the field "observatory.LSA24M5.feeds.temperatures.Channel_3_V" in the data file `/mnt/so1/data/ucsd-sat1/hk/16151/1615148969.g3` on simons1.

When loading with the cell:
```
start, stop = (1615149004.726616, 1615149005.3551733)
field = 'observatory.LSA24M5.feeds.temperatures.Channel_3_V'
hk = load_range(start, stop, data_dir="/mnt/so1/data/ucsd-sat1/hk", fields=['observatory.LSA24M5.feeds.temperatures.Channel_3_V'])
```
Then the data returned is 
```
hk[field][1]
>> array([2220, 2220, 2220, ..., 2337, 2337, 2337], dtype=int64)
```
I'm pretty sure that this isn't a problem for all fields, since we would've noticed. I think it's just an instance of the dtype detection [here](https://github.com/simonsobs/so3g/blob/master/python/hk/getdata.py#L335) failing for some reason.

I've compared the G3 data with the data being returned, and can see that the G3 data looks right and the casting happens in the load function:
![image](https://user-images.githubusercontent.com/4718487/111240172-1ad8b180-85d1-11eb-9978-f727ea47e4f9.png)

**Comment by jlashner** [comment]
We figured out that the problem is possibly caused by the modified agent at UCSD which attempted to re-initialize the lakeshore after the connection dropped (on the [ls240-dropout branch](https://github.com/simonsobs/socs/tree/LS240_dropout)

It added [these lines](https://github.com/simonsobs/socs/blob/LS240_dropout/agents/lakeshore240/LS240_agent.py#L249-L261) which unintentionally sent integer-zeros on failure. This could be the reason why the loader was misinterpreting the datatype. We've since switched back to the regular ls240 image, so hopefully this doesn't happen again.

Is there any chance we can modify the data loader so it can correctly load this data segment? Or should we just do this analysis segment manually with G3 files?

**Comment by mhasself** [comment]
I would prefer a general approach to "modifying the loader so it can X" rather than a specific one...  For example, an input file to the archiver / loader that tells it to ignore certain fields over certain time ranges.  I assume that's all you need to do in this case.  This model is expandable for weirder things in the future... e.g. renaming fields over certain time ranges.

**Comment by jlashner** [comment]
Would you be opposed to adding a `dtypes` argument that lets you override the dtype determination?

**Comment by mhasself** [comment]
I'm against it if it needs to permeate all the logic and adds a lot of spaghetti...  if it's just a kwarg and a few lines to control casting, I won't fight it.

**Comment by mhasself** [comment]
I think we've moved on!
